# SPDX-License-Identifier: MIT
openapi: 3.0.3
info:
  title: OpenWeatherMap Air Pollution API (Draft)
  version: 0.2.0-draft
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: |
    Draft specification for OpenWeatherMap Air Pollution API.
    Source: official OpenWeather Air Pollution documentation.
servers:
  - url: https://api.openweathermap.org
    description: OpenWeather production API
security:
  - AppIdQueryAuth: []
paths:
  /data/2.5/air_pollution:
    get:
      operationId: getCurrentAirPollution
      summary: Current air pollution
      description: Returns current air pollution data for a location.
      parameters:
        - $ref: '#/components/parameters/Lat'
        - $ref: '#/components/parameters/Lon'
      responses:
        '200':
          description: Current air pollution returned successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirPollutionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /data/2.5/air_pollution/forecast:
    get:
      operationId: getAirPollutionForecast
      summary: Air pollution forecast
      description: Returns forecasted air pollution data for a location.
      parameters:
        - $ref: '#/components/parameters/Lat'
        - $ref: '#/components/parameters/Lon'
      responses:
        '200':
          description: Air pollution forecast returned successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirPollutionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /data/2.5/air_pollution/history:
    get:
      operationId: getAirPollutionHistory
      summary: Historical air pollution
      description: Returns historical air pollution data for a location and time range.
      parameters:
        - $ref: '#/components/parameters/Lat'
        - $ref: '#/components/parameters/Lon'
        - $ref: '#/components/parameters/Start'
        - $ref: '#/components/parameters/End'
      responses:
        '200':
          description: Historical air pollution returned successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirPollutionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  securitySchemes:
    AppIdQueryAuth:
      type: apiKey
      in: query
      name: appid

  parameters:
    Lat:
      name: lat
      in: query
      required: true
      description: Latitude in decimal degrees.
      schema:
        type: number
        format: double
        minimum: -90
        maximum: 90
    Lon:
      name: lon
      in: query
      required: true
      description: Longitude in decimal degrees.
      schema:
        type: number
        format: double
        minimum: -180
        maximum: 180
    Start:
      name: start
      in: query
      required: true
      description: UNIX timestamp for start of interval.
      schema:
        type: integer
        format: int64
    End:
      name: end
      in: query
      required: true
      description: UNIX timestamp for end of interval.
      schema:
        type: integer
        format: int64

  responses:
    BadRequest:
      description: Invalid request parameters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid API key.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: No data found for requested parameters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TooManyRequests:
      description: Request quota exceeded.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Server-side error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ErrorResponse:
      type: object
      required: [message]
      properties:
        cod:
          oneOf:
            - type: integer
            - type: string
        message:
          type: string

    CoordinatesObject:
      type: object
      required: [lon, lat]
      properties:
        lon:
          type: number
          format: double
        lat:
          type: number
          format: double

    Coordinates:
      description: Coordinate payload as documented across OpenWeather examples.
      oneOf:
        - $ref: '#/components/schemas/CoordinatesObject'
        - type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
            format: double

    AirQualityIndex:
      type: object
      required: [aqi]
      properties:
        aqi:
          type: integer
          minimum: 1
          maximum: 5

    PollutantComponents:
      type: object
      required: [co, no, no2, o3, so2, pm2_5, pm10, nh3]
      properties:
        co:
          type: number
          format: double
        no:
          type: number
          format: double
        no2:
          type: number
          format: double
        o3:
          type: number
          format: double
        so2:
          type: number
          format: double
        pm2_5:
          type: number
          format: double
        pm10:
          type: number
          format: double
        nh3:
          type: number
          format: double

    AirPollutionItem:
      type: object
      required: [main, components, dt]
      properties:
        main:
          $ref: '#/components/schemas/AirQualityIndex'
        components:
          $ref: '#/components/schemas/PollutantComponents'
        dt:
          type: integer
          format: int64

    AirPollutionResponse:
      type: object
      required: [coord, list]
      properties:
        coord:
          $ref: '#/components/schemas/Coordinates'
        list:
          type: array
          items:
            $ref: '#/components/schemas/AirPollutionItem'
