# SPDX-License-Identifier: MIT
openapi: 3.0.3
info:
  title: OpenWeatherMap 5 Day / 3 Hour Forecast API (Draft)
  version: 0.1.0-draft
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: Draft specification for OpenWeatherMap Forecast API.
servers:
  - url: https://api.openweathermap.org
paths: {}
components: {}
