openapi: 3.0.3
info:
  title: OpenWeatherMap Geocoding API (Draft)
  version: 0.1.0-draft
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: Draft specification for OpenWeatherMap Geocoding API.
servers:
  - url: https://api.openweathermap.org
paths: {}
components: {}
