# SPDX-License-Identifier: MIT
openapi: 3.0.3
info:
  title: OpenWeatherMap Geocoding API (Draft)
  version: 0.2.0-draft
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: |
    Draft specification for OpenWeatherMap Geocoding API.
    Source: official OpenWeather Geocoding documentation.
servers:
  - url: https://api.openweathermap.org
    description: OpenWeather production API
security:
  - AppIdQueryAuth: []
paths:
  /geo/1.0/direct:
    get:
      operationId: getDirectGeocoding
      summary: Direct geocoding
      description: Returns a list of locations matching a textual query.
      parameters:
        - $ref: '#/components/parameters/Query'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: Locations returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeocodingLocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /geo/1.0/reverse:
    get:
      operationId: getReverseGeocoding
      summary: Reverse geocoding
      description: Returns a list of locations for provided latitude and longitude.
      parameters:
        - $ref: '#/components/parameters/Lat'
        - $ref: '#/components/parameters/Lon'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: Locations returned successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeocodingLocation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /geo/1.0/zip:
    get:
      operationId: getZipGeocoding
      summary: ZIP/post code geocoding
      description: Returns geocoding information for a ZIP or postal code.
      parameters:
        - $ref: '#/components/parameters/Zip'
      responses:
        '200':
          description: ZIP geocoding returned successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZipGeocodingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  securitySchemes:
    AppIdQueryAuth:
      type: apiKey
      in: query
      name: appid

  parameters:
    Query:
      name: q
      in: query
      required: true
      description: Free-form location query (city/state/country form).
      schema:
        type: string
    Limit:
      name: limit
      in: query
      required: false
      description: Number of returned locations.
      schema:
        type: integer
        minimum: 1
        maximum: 5
    Lat:
      name: lat
      in: query
      required: true
      description: Latitude in decimal degrees.
      schema:
        type: number
        format: double
        minimum: -90
        maximum: 90
    Lon:
      name: lon
      in: query
      required: true
      description: Longitude in decimal degrees.
      schema:
        type: number
        format: double
        minimum: -180
        maximum: 180
    Zip:
      name: zip
      in: query
      required: true
      description: ZIP or postal code, optionally with country code (e.g. 94040,US).
      schema:
        type: string

  responses:
    BadRequest:
      description: Invalid request parameters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid API key.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: No data found for requested parameters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TooManyRequests:
      description: Request quota exceeded.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Server-side error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ErrorResponse:
      type: object
      required: [message]
      properties:
        cod:
          oneOf:
            - type: integer
            - type: string
        message:
          type: string

    LocalNames:
      type: object
      description: Localized names keyed by language code.
      additionalProperties:
        type: string

    GeocodingLocation:
      type: object
      required: [name, lat, lon, country]
      properties:
        name:
          type: string
        local_names:
          $ref: '#/components/schemas/LocalNames'
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
        country:
          type: string
        state:
          type: string

    ZipGeocodingResponse:
      type: object
      required: [zip, name, lat, lon, country]
      properties:
        zip:
          type: string
        name:
          type: string
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
        country:
          type: string
