;; SPDX-License-Identifier: MIT
(defpackage :openweathermap
  (:use :cl)
  (:export
   :*api-base-url*
   :*maps-base-url*
   :*api-key*
   :*request-timeout-seconds*
   :*max-retries*
   :*retry-backoff-seconds*
   :configure-api-key
   :configure-client
   :with-http-get-function
   :missing-api-key-error
   :api-request-error
   :api-network-error
   :api-response-parse-error
   :invalid-parameters-error
   :build-onecall-url
   :build-timemachine-url
   :build-day-summary-url
   :build-overview-url
   :make-client-weather-request
   :make-timemachine-request
   :make-day-summary-request
   :make-overview-request
   :fetch-onecall
   :fetch-timemachine
   :fetch-day-summary
   :fetch-overview
   :build-current-weather-url
   :make-current-weather-request
   :fetch-current-weather
   :build-forecast-url
   :make-forecast-request
   :fetch-forecast
   :build-geocoding-url
   :make-geocoding-request
   :fetch-geocoding
   :build-reverse-geocoding-url
   :make-reverse-geocoding-request
   :fetch-reverse-geocoding
   :build-zip-geocoding-url
   :make-zip-geocoding-request
   :fetch-zip-geocoding
   :build-air-pollution-url
   :make-air-pollution-request
   :fetch-air-pollution
   :build-air-pollution-forecast-url
   :make-air-pollution-forecast-request
   :fetch-air-pollution-forecast
   :build-air-pollution-history-url
   :make-air-pollution-history-request
   :fetch-air-pollution-history
   :build-weather-tile-url
   :make-weather-tile-request
   :fetch-weather-tile
   :lookup-weather-condition
   :weather-icon-url
   :resolve-weather-condition
   :enrich-weather-entry
   :enrich-weather-list
   :ensure-api-key))
